BEGIN;

-- Usuários existentes recebem e-mail temporário para preservar os registros.
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS subject VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS shift VARCHAR(10);
UPDATE users SET email = 'legacy-' || id || '@change.local' WHERE email IS NULL;
ALTER TABLE users ALTER COLUMN email SET NOT NULL;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_name_key;
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email ON users (LOWER(email));
CREATE INDEX IF NOT EXISTS ix_users_shift ON users (shift);

-- Salas antigas são inicialmente associadas ao turno da manhã.
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS shift VARCHAR(10);
UPDATE rooms SET shift = 'MANHA' WHERE shift IS NULL;
UPDATE rooms SET lesson_count = 7 WHERE lesson_count < 7;
UPDATE rooms SET lesson_count = 16 WHERE lesson_count > 16;
ALTER TABLE rooms ALTER COLUMN shift SET NOT NULL;
CREATE INDEX IF NOT EXISTS ix_rooms_shift ON rooms (shift);

-- Horários antigos são calculados a partir do número da aula.
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS class_time TIME;
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'AGENDADA';
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS cancelled_by_id INTEGER REFERENCES users(id);
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ;
UPDATE schedules
SET class_time = TIME '07:00' + ((lesson_number - 1) * INTERVAL '1 hour')
WHERE class_time IS NULL;
UPDATE schedules SET status = 'AGENDADA' WHERE status IS NULL;
ALTER TABLE schedules ALTER COLUMN class_time SET NOT NULL;
ALTER TABLE schedules ALTER COLUMN status SET NOT NULL;

CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(150) NOT NULL,
    message VARCHAR(500) NOT NULL,
    read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS ix_notifications_created_at ON notifications(created_at);

DO $$ BEGIN
    ALTER TABLE users ADD CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'PROFESSOR'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE users ADD CONSTRAINT ck_users_shift CHECK (shift IS NULL OR shift IN ('MANHA', 'TARDE', 'NOITE'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE rooms ADD CONSTRAINT ck_rooms_shift CHECK (shift IN ('MANHA', 'TARDE', 'NOITE'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE rooms ADD CONSTRAINT ck_rooms_lesson_count CHECK (lesson_count BETWEEN 7 AND 16);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE schedules ADD CONSTRAINT ck_schedules_status CHECK (status IN ('AGENDADA', 'CONFIRMADA', 'CANCELADA'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

COMMIT;

-- IMPORTANTE: substitua os e-mails temporários após executar a migração.
-- Exemplo:
-- UPDATE users SET email = 'admin@escola.com' WHERE role = 'ADMIN';
-- UPDATE users SET email = 'professor@escola.com', subject = 'Matemática',
--                  shift = 'MANHA' WHERE id = 2;

